### ISSUE TITLE
Getting this error with your new commit

### ISSUE THREAD

**Issue by Bazookan** [ESX-Org/es_extended#157]
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:379: server/main.lua:156: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:156: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:365: in function <citizen:/scripting/lua/scheduler.lua:364>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:364: in function <citizen:/scripting/lua/scheduler.lua:363>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:379: in function <citizen:/scripting/lua/scheduler.lua:348>
Error: Unhandled error: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:11
    at setImmediate (mysql-async.js:4962:9)
    at Object.callback (citizen:/scripting/v8/timer.js:56:6)
Error running call reference function for resource esx_tattoshop: citizen:/scripting/lua/scheduler.lua:379: server/main.lua:10: attempt to index a nil value (local 'xPlayer')
stack traceback:
        server/main.lua:10: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:365: in function <citizen:/scripting/lua/scheduler.lua:364>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:364: in function <citizen:/scripting/lua/scheduler.lua:363>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:379: in function <citizen:/scripting/lua/scheduler.lua:348>
Error running system event handling function for resource es_extended: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
        citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
        citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
        citizen:/scripting/lua/scheduler.lua:602: in field '?'
        server/functions.lua:33: in field 'TriggerServerCallback'
        server/common.lua:63: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:195: in function <citizen:/scripting/lua/scheduler.lua:194>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:194: in function <citizen:/scripting/lua/scheduler.lua:158>
Error running system event handling function for resource jsfour-legitimation: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server.lua:8: attempt to index a nil value
stack traceback:
        server.lua:8: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:195: in function <citizen:/scripting/lua/scheduler.lua:194>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:194: in function <citizen:/scripting/lua/scheduler.lua:158>

**Comment by Bazookan** [comment]
Update: changing back to, MySQL.Async.fetchAll('SELECT * FROM `users` WHERE `identifier` = @identifier', {
fixed it. So there is something wrong with your latest commit.
