### ISSUE TITLE
Connecting ERROR

### ISSUE THREAD

**Issue by Ffrankys** [ESX-Org/es_extended#165]
Connecting: Ucrited
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:359: server/main.lua:156: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:156: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:345: in function <citizen:/scripting/lua/scheduler.lua:344>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:344: in function <citizen:/scripting/lua/scheduler.lua:343>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:359: in function <citizen:/scripting/lua/scheduler.lua:328>
Error: Unhandled error: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:11
    at setImmediate (mysql-async.js:5039:9)
    at Object.callback (citizen:/scripting/v8/timer.js:56:6)

**Comment by HumanTree92** [comment]
Do you know how you fixed this?
