### ISSUE TITLE
Error at the connecting

### ISSUE THREAD

**Issue by ItsTopix** [ESX-Org/es_extended#210]
I Connect to the Server and :

Connecting: ItsTopix
Sending heartbeat to live-internal.fivem.net:30110
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: server/main.lua:169: attempt to index a nil value (field '?')
stack traceback:
        server/main.lua:169: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:389: in function <citizen:/scripting/lua/scheduler.lua:388>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:388: in function <citizen:/scripting/lua/scheduler.lua:387>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:403: in function <citizen:/scripting/lua/scheduler.lua:372>
Error: Unhandled error in timer: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:11
    at setImmediate (mysql-async.js:4962:9)
    at Object.callback (citizen:/scripting/v8/timer.js:96:21)

Can someone help me?

**Comment by x0Z3ro0x** [comment]
Same issue here:

https://github.com/ESX-Org/es_extended/issues/221

I provided more details so hopefully we get an answer. When all you do is say you have an error and past it. It does nothing to help find out how to solve or reproduce the error.
