### ISSUE TITLE
Please tell me how to fix the error running call reference function

### ISSUE THREAD

**Issue by Pakrjiyu1101** [ESX-Org/es_extended#305]
![1887b3daec35c316](https://user-images.githubusercontent.com/52248846/60188092-af353a80-9869-11e9-9350-39d6af2af44b.png)
Please tell me how to fix the error running call reference function
I can't open the server with this problem. Please help me.

**Comment by tilexD** [comment]
I can open the server but I dont have HUD(ex. cash,bank,dirty_money, doesnt see current job, ... ) also my inventory doesnt work. This error came when I was puting vMenu files and  vMenu.sql into my database. Any ideas? pls help (before vMenu server works properly). Now I tried removed the vMenu and error still come. Any help will be aappreciated. :)

Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:405: @es_extended/server/main.lua:61: attempt to index a nil value (field '?')
stack traceback:
        @es_extended/server/main.lua:61: in upvalue 'ref'
        citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390>
        [C]: in function 'xpcall'
        citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374>
Error: Unhandled error in timer: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:20
    at setImmediate (mysql-async.js:14898:7)
    at Object.callback (citizen:/scripting/v8/timer.js:96:21)
