### ISSUE TITLE
Major Problem

### ISSUE THREAD

**Issue by SidVicious99** [ESX-Org/es_extended#412]
Error running call reference function for resource es_extended: citizen:/scripting/lua/scheduler.lua:403: server/main.lua:62: attempt to index a nil value (field '?')
stack traceback:
    server/main.lua:62: in upvalue 'ref'
    citizen:/scripting/lua/scheduler.lua:389: in function citizen:/scripting/lua/scheduler.lua:388
    [C]: in function 'xpcall'
    citizen:/scripting/lua/scheduler.lua:388: in function citizen:/scripting/lua/scheduler.lua:387
stack traceback:
    [C]: in function 'error'
    citizen:/scripting/lua/scheduler.lua:403: in function citizen:/scripting/lua/scheduler.lua:372
Error: Unhandled error: Error: BUFFER_SHORTAGE
Error: BUFFER_SHORTAGE
    at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766)
    at h (citizen:/scripting/v8/msgpack.js:29:15761)
    at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908)
    at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972)
    at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076)
    at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097)
    at unpack (citizen:/scripting/v8/main.js:20:33)
    at citizen:/scripting/v8/main.js:51:11
    at setImmediate (mysql-async.js:4962:9)
    at Object.callback (citizen:/scripting/v8/timer.js:56:6)

**Comment by SidVicious99** [comment]
No idea what happened or why this error has occurred. I didn't change anything, restarted my server then this error started. When I load in it spawns me in a random location with my inventory cleared.
